version: "3"
services:
  app:
    image: sebwink/flask-deploy-test
    build: .
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-5000}
      DEPLOY: ${DEPLOY:-}
    ports:
      - '5000:5000/tcp'
